### ISSUE TITLE
Failures when testing the googleapis generated package (starting after the 10th test)

### ISSUE THREAD

**Issue by sgjesse** [google/test_runner.dart#27]
The generated tests in the generated googleapis package fails when using test_runner.

There are the steps to run the tests and see the failures:

```
$ git clone https://github.com/dart-lang/googleapis.git
$ cd googleapis
$ pub global activate test_runner
$ cd generated/googleapis
$ pub global run test_runner
```
The tests will now run, but only the first 10 will succeed.
```
Checking Dart SDK binaries...
Dart SDK binaries OK.

Looking for Dart project in "./"...
Found project "googleapis".

Looking for test suites...
Found 62 test suites (62 Standalone VM, 0 Dartium).  

Running all tests...
Test suite passed: admin/email_migration_v2_test.dart
Test suite passed: adexchangeseller/v2_0_test.dart
Test suite passed: adexchangeseller/v1_1_test.dart
Test suite passed: adsensehost/v4_1_test.dart
Test suite passed: adexchangebuyer/v1_3_test.dart
Test suite passed: admin/reports_v1_test.dart
Test suite passed: adsense/v1_4_test.dart
Test suite passed: admin/directory_v1_test.dart
Test suite passed: appsactivity/v1_test.dart
Test suite failed: appstate/v1_test.dart
Detailed results of test suite appstate/v1_test.dart:
┌────────────────────────────────────────────────────
│ 
│ Unhandled exception:
│ No top-level getter 'main' declared.
│ 
│ NoSuchMethodError: method not found: 'main'
│ Receiver: top-level
│ Arguments: [...]
│ #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:176)
│ #1      _getMainClosure (dart:_builtin:97)
└────────────────────────────────────────────────────
Test suite failed: androidpublisher/v2_test.dart
Detailed results of test suite androidpublisher/v2_test.dart:
┌────────────────────────────────────────────────────────────
│ 
│ Unhandled exception:
│ No top-level getter 'main' declared.
│ 
│ NoSuchMethodError: method not found: 'main'
│ Receiver: top-level
│ Arguments: [...]
│ #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:176)
│ #1      _getMainClosure (dart:_builtin:97)
└────────────────────────────────────────────────────────────
Test suite failed: bigquery/v2_test.dart
Detailed results of test suite bigquery/v2_test.dart:
┌────────────────────────────────────────────────────
│ 
│ Unhandled exception:
│ No top-level getter 'main' declared.
│ 
│ NoSuchMethodError: method not found: 'main'
│ Receiver: top-level
│ Arguments: [...]
│ #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:176)
│ #1      _getMainClosure (dart:_builtin:97)
└────────────────────────────────────────────────────
```
From here it continues with `No top-level getter 'main' declared.` errors. All tests have `main` methods.

This is using Dart SDK 1.9.0-dev.8.0 and test_runner 0.2.15+2 on OS X.

Testing the `googleapis_beta` package have the same issue - tests after test number 10 fails.

**Comment by nicolasgarnier** [comment]
Hey Soren,

i'm investigating. Question: are the failure consistant? i.e. always the same tests fail at each run?

**Comment by nicolasgarnier** [comment]
Weird, just went through the steps above to try to replicate. I got this:

`Summary: ALL 62 TEST SUITE(S) PASSED.`

Trying again...

**Comment by nicolasgarnier** [comment]
Actually on my second run 2 tests failed so it seems a bit random... I'm looking into it.

**Comment by nicolasgarnier** [comment]
It's weird: it's random. I can't reproduce when running the tests individually with the generated files... Looks like a problem happening only when running lots of instances of `dart` in parallel (maybe...)

**Comment by nicolasgarnier** [comment]
I think I fixed it. There was a place where we were not waiting for the temporary test files to be created before running the VM tests... You can update to 0.2.15+3

**Comment by nicolasgarnier** [comment]
Thanks again for the report!

**Comment by sgjesse** [comment]
It all works now! Thanks!
